"""
论文写作系统VO层
"""
# AI模型相关VO
from module_thesis.entity.vo.ai_model_vo import (
    AiModelConfigModel,
    AiModelConfigPageQueryModel,
    AiModelConfigQueryModel,
    AiModelTestRequestModel,
    AiModelTestResponseModel,
)

# 会员相关VO
from module_thesis.entity.vo.member_vo import (
    DeductQuotaModel,
    MemberPackageModel,
    MemberPackagePageQueryModel,
    MemberPackageQueryModel,
    MemberPackageResponseModel,
    QuotaRecordModel,
    QuotaRecordPageQueryModel,
    QuotaRecordQueryModel,
    UserFeatureQuotaModel,
    UserFeatureQuotaPageQueryModel,
    UserFeatureQuotaQueryModel,
    UserMembershipModel,
    UserMembershipPageQueryModel,
    UserMembershipQueryModel,
    UserQuotaInfoModel,
)

# 订单相关VO
from module_thesis.entity.vo.order_vo import (
    CreateOrderModel,
    ExportRecordDetailModel,
    ExportRecordModel,
    ExportRecordPageQueryModel,
    ExportRecordQueryModel,
    ExportThesisModel,
    FeatureServiceModel,
    FeatureServicePageQueryModel,
    FeatureServiceQueryModel,
    OrderDetailResponseModel,
    OrderModel,
    OrderPageQueryModel,
    OrderQueryModel,
    OrderStatisticsModel,
    PaymentCallbackModel,
    PaymentResultModel,
    PurchaseFeatureServiceModel,
    RefundOrderModel,
)

# 模板相关VO
from module_thesis.entity.vo.template_vo import (
    AddFormatRuleModel,
    BatchAddFormatRulesModel,
    DeleteTemplateModel,
    FormatTemplateModel,
    PopularTemplateModel,
    TemplateDetailResponseModel,
    TemplateFormatRuleModel,
    TemplateListItemModel,
    TemplatePageQueryModel,
    TemplateQueryModel,
    TemplateUpdateModel,
    TemplateUploadModel,
    UpdateFormatRuleModel,
)

# 论文相关VO
from module_thesis.entity.vo.thesis_vo import (
    CreateVersionModel,
    DeleteThesisModel,
    GenerateChapterModel,
    GenerateOutlineModel,
    RestoreVersionModel,
    ThesisChapterModel,
    ThesisCreateModel,
    ThesisDetailResponseModel,
    ThesisListItemModel,
    ThesisModel,
    ThesisOutlineModel,
    ThesisPageQueryModel,
    ThesisQueryModel,
    ThesisUpdateModel,
    ThesisVersionModel,
    UpdateChapterModel,
    UpdateOutlineModel,
)

__all__ = [
    # AI模型相关VO
    'AiModelConfigModel',
    'AiModelConfigQueryModel',
    'AiModelConfigPageQueryModel',
    'AiModelTestRequestModel',
    'AiModelTestResponseModel',
    # 会员相关VO
    'MemberPackageModel',
    'MemberPackageQueryModel',
    'MemberPackagePageQueryModel',
    'MemberPackageResponseModel',
    'UserMembershipModel',
    'UserMembershipQueryModel',
    'UserMembershipPageQueryModel',
    'UserFeatureQuotaModel',
    'UserFeatureQuotaQueryModel',
    'UserFeatureQuotaPageQueryModel',
    'DeductQuotaModel',
    'QuotaRecordModel',
    'QuotaRecordQueryModel',
    'QuotaRecordPageQueryModel',
    'UserQuotaInfoModel',
    # 论文相关VO
    'ThesisModel',
    'ThesisCreateModel',
    'ThesisUpdateModel',
    'ThesisQueryModel',
    'ThesisPageQueryModel',
    'DeleteThesisModel',
    'ThesisOutlineModel',
    'GenerateOutlineModel',
    'UpdateOutlineModel',
    'ThesisChapterModel',
    'GenerateChapterModel',
    'UpdateChapterModel',
    'ThesisVersionModel',
    'CreateVersionModel',
    'RestoreVersionModel',
    'ThesisDetailResponseModel',
    'ThesisListItemModel',
    # 模板相关VO
    'FormatTemplateModel',
    'TemplateUploadModel',
    'TemplateUpdateModel',
    'TemplateQueryModel',
    'TemplatePageQueryModel',
    'DeleteTemplateModel',
    'TemplateFormatRuleModel',
    'AddFormatRuleModel',
    'UpdateFormatRuleModel',
    'BatchAddFormatRulesModel',
    'TemplateDetailResponseModel',
    'TemplateListItemModel',
    'PopularTemplateModel',
    # 订单相关VO
    'OrderModel',
    'CreateOrderModel',
    'OrderQueryModel',
    'OrderPageQueryModel',
    'PaymentCallbackModel',
    'RefundOrderModel',
    'FeatureServiceModel',
    'FeatureServiceQueryModel',
    'FeatureServicePageQueryModel',
    'PurchaseFeatureServiceModel',
    'ExportRecordModel',
    'ExportThesisModel',
    'ExportRecordQueryModel',
    'ExportRecordPageQueryModel',
    'OrderDetailResponseModel',
    'PaymentResultModel',
    'OrderStatisticsModel',
    'ExportRecordDetailModel',
]
